#!/usr/bin/env julia

using ArgParse

include("../src/analyzeknownsllist.jl")

function parse_commandline()
    s = ArgParseSettings("This interface is used for analyzing the Synthetic Lethal pairs in the SL database that are found within a specified pairwise interaction file.",
                         version = "0.0.1",
                         add_version = true)

    @add_arg_table s begin
        "--downregulated-cutoff"
            help = "This determines at which level the node is determined to be down regulated."
            arg_type = Float64
            default = 0.99
        "--lowerbound", "-l"
            arg_type = Float64
            default = 0.001
        "--verbose", "-v"
            help = "This will cause output to be printed to standard out."
            action = :store_true
        "pairwise-interaction-file"
            help = "This is the full path to the pairwise interaction file."
            required = true
        "sl-results-file"
            help = "This file will be generated by this script."
            required = true
        "db-id-file"
            help = "This is file contains a mapping between pathaway IDs, gene names and Reactome IDs"
            required = true
    end

    return parse_args(s)
end

function main()
    parsed_args = parse_commandline()

    if parsed_args["verbose"]
        println("Parsed args:")
        for (arg,val) in parsed_args
            println("  $arg  =>  $val")
        end
    end

    AnalyzeKnownSLList.run(parsed_args["pairwise-interaction-file"],
                           parsed_args["sl-results-file"],
                           parsed_args["lowerbound"],
                           parsed_args["upperbound"],
                           parsed_args["db-id-file"],
                           parsed_args["verbose"])
end

main()
