sudo: required

services:
      - docker

install:
      - docker pull oicr/mpbiopath-env:1.0.4-SNAPSHOT

script:
    - docker build -t mpbiopath -f docker/Dockerfile.app .
    - docker run mpbiopath make run-tests
