sudo: required

services:
      - docker

install:
      - docker pull oicr/mpbiopath-env:0.0.4-SNAPSHOT

script:
    - docker build -t mpbiopath -f docker/Dockerfile.app .
    - docker run mpbiopath julia test/run.jl
