FROM julia:0.6.1

ENV DEBIAN_FRONTEND noninteractive

RUN mkdir /install-scripts

COPY scripts/INSTALL.jl /scripts/

RUN apt-get update -y

RUN apt-get install software-properties-common -y

#RUN add-apt-repository -y ppa:staticfloat/juliareleases
#RUN add-apt-repository -y ppa:staticfloat/julia-deps

RUN apt-get update && apt-get upgrade -y
RUN apt-get install build-essential  gfortran pkg-config wget libnlopt0 unzip -y

# For Julia FactCheck - I think
RUN apt-get install libfontconfig1 -y

# For Julia Cairo package
RUN apt-get install gettext -y

# For creating heatmaps
RUN apt-get install r-base libstatistics-r-perl r-cran-ggplot2 -y

RUN apt-get install vim -y

ENV MAKEFLAGS -j4

RUN cd /scripts && julia INSTALL.jl;
