FROM julia:1.1.0

RUN mkdir /install-scripts

COPY INSTALL.jl /install-scripts/

# For creating heatmaps
#RUN apt-get install r-base libstatistics-r-perl r-cran-ggplot2 r-cran-gplots -y

#RUN apt-get install vim -y

RUN cd /install-scripts && julia INSTALL.jl;
