Pkg.update()
Pkg.add("JuMP")
Pkg.add("ArgParse")
Pkg.add("Ipopt")
Pkg.add("Cbc")
Pkg.add("NLopt")
Pkg.add("CoinOptServices")
Pkg.add("AmplNLWriter")
Pkg.add("Requests")
Pkg.add("FactCheck")
Pkg.add("CSV")
Pkg.add("YAML")
Pkg.add("JSON")
Pkg.add("DocOpt")
Pkg.add("DataFrames")

#for tsne
Pkg.add("Gadfly")
Pkg.add("Cairo")
Pkg.add("Fontconfig")
